# Generated by Django 5.2.7 on 2026-10-10 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_newsletter_unsubscribe_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # limit_choices_to опирается на группы ролей сотрудников.
        ("users", "0023_staff_role_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerroutingrule",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Учётная запись ответственного менеджера; письма уходят на её email",
                limit_choices_to=models.Q(
                    ("groups__name__in", ("Менеджеры", "Руководители")), ("is_staff", True), ("is_superuser", False)
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routing_rules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="managerroutingrule",
            name="manager_email",
            field=models.EmailField(
                blank=True,
                help_text="Адрес, на который уходит уведомление о регистрации. Используется, пока менеджер не выбран",
                max_length=254,
                verbose_name="Email менеджера",
            ),
        ),
        migrations.AddConstraint(
            model_name="managerroutingrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("match_type__in", ["inn_region", "country"])),
                fields=("match_type", "match_value"),
                name="common_mrr_one_active_per_key",
                violation_error_message="Для этого кода региона или страны уже есть активное правило. Выключите его или измените.",
            ),
        ),
        migrations.AddConstraint(
            model_name="managerroutingrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("manager__isnull", False), ("match_type", "fallback")),
                fields=("match_type",),
                name="common_mrr_one_fallback_manager",
                violation_error_message="Ответственного по резервному правилу может давать только одно активное правило с менеджером.",
            ),
        ),
    ]
