# Generated by Django 5.2.7 on 2026-10-10 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0023_link_routing_rules_to_staff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="managerroutingrule",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Учётная запись ответственного менеджера; письма уходят на её email",
                limit_choices_to=models.Q(
                    ("groups__name__in", ("Менеджеры", "Руководители")), ("is_staff", True), ("is_superuser", False)
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routing_rules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
    ]
