# Generated by Django 5.2.7 on 2026-10-10 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_staff_role_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="responsible_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("groups__name__in", ("Менеджеры", "Руководители")), ("is_staff", True), ("is_superuser", False)
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный менеджер",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="responsible_manager_manual",
            field=models.BooleanField(
                default=False,
                help_text="Ручное назначение не перезаписывают правила регионов, смена ИНН и импорт 1С",
                verbose_name="Назначен вручную",
            ),
        ),
    ]
