# Generated by Django 5.2.7 on 2026-10-10 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_user_responsible_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="responsible_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("groups__name__in", ("Менеджеры", "Руководители")), ("is_staff", True), ("is_superuser", False)
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный менеджер",
            ),
        ),
    ]
